### ISSUE TITLE
Not working anymore since last VsCode update

### ISSUE THREAD

**Issue by Vince1024** [mondersky/tabscolor-vscode#32]
Hi all,

Since VsCode has update this morning my TABS COLOR extension is not working at all.

No colors I have in my config file and neither colors when right-click on tabs and choose a color.

Is it a known issue ?

Thanks.

`
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
`

**Comment by mondersky** [comment]
thanks for reporting this. I am currently I'm presently in the process of addressing the update

**Comment by boromyr** [comment]
Updated to version v0.1.36 but the issue still persists for me.

**Comment by mondersky** [comment]
version 0.1.36 doesn't include any fix, it simply features a popup to notify users that the issue is being addressed.

**Comment by canferman** [comment]
Will there be a new update ro fix this?

**Comment by mondersky** [comment]
the fix has been released, Could you verify that it is functioning on your VsCode ?

**Comment by Vince1024** [comment]
Hi 
Many thanks, it works fine for me.

**Comment by boromyr** [comment]
It works for me, but not for the tabs where I had set the color in previous versions, where are the settings for the tab colors saved so I can delete them to completely reset the extension? Reinstalling did not solve the problem.

**Comment by mondersky** [comment]
> It works for me, but not for the tabs where I had set the color in previous versions, where are the settings for the tab colors saved so I can delete them to completely reset the extension? Reinstalling did not solve the problem.

The previously saved colors are supposed to remain after the update but if you want to erase them press ctrl+p and type tabsColor functions: clear all tabs color
as for the settings, you can find them in the user settings json file of your VsCode

**Comment by mondersky** [comment]
you're all welcome, consider taking a moment to share your experience through a review, this will support the promotion of the extension. Thanks
